brawl:
  DisplayName: Brawling
  Shorthand: Brawl
  Description: Fight hostile monsters in close combat, ideally with your sword.
breed:
  DisplayName: Breeding
  Shorthand: Breed
  Description: Feed your farm animals to make them breed and increase their numbers.
brew:
  DisplayName: Brewing
  Shorthand: Brew
  Description: Brew magic potions in the brewing stand to achieve epic effects or wreak havoc on your enemies.
build:
  DisplayName: Building
  Shorthand: Build
  Description: Place blocks in the world to make your own epic creations.
butcher:
  DisplayName: Butchery
  Shorthand: Butcher
  Description: Butcher your farm animals to harvest their precious drops.
cook:
  DisplayName: Cooking
  Shorthand: Cook
  Description: Prepare your meals in the oven to increase their effectiveness and tase.
dig:
  DisplayName: Digging
  Shorthand: Dig
  Description: Use your shovel to dig in the ground and find epic treasure hidden beneath.
eat:
  DisplayName: Eating
  Shorthand: Eat
  Description: Eat healthy and tasty food to maintain your stamina, heal up and refresh.
enchant:
  DisplayName: Enchanting
  Shorthand: Enchant
  Description: Improve your weapons, tools and armor on the enchanting table to make them stronger, more effective and deadlier.
fish:
  DisplayName: Fishing
  Shorthand: Fish
  Description: Cast your fishing rod in bodies of water to catch different types of fish for food or brewing.
harvest:
  DisplayName: Harvesting
  Shorthand: Harvest
  Description: Reap the rewards of your hard gardening work by harvesting cereal, fruit and vegetables.
hunt:
  DisplayName: Hunting
  Shorthand: Hunt
  Description: Snipe dangerous creatures from afar with your bow to stay out of harms way.
mine:
  DisplayName: Mining
  Shorthand: Mine
  Description: Grab your pickaxe and descend into the deep mines of this world to find precious ores and rare gems.
quaff:
  DisplayName: Quaffing
  Shorthand: Quaff
  Description: Drink powerful potions to make you stronger, faster or deadlier.
sacrifice:
  DisplayName: Sacrifice
  Shorthand: Sacrifice
  Description: Sacrifice your precious offerings to the almighty Creeper Overlord in exchange for his blessing.
smelt:
  DisplayName: Smelting
  Shorthand: Smelt
  Description: Refine your ores and raw materials in a furnace to make them even more precious and useful.
travel:
  DisplayName: Traveling
  Shorthand: Travel
  Description: Leave your home and travel out in the world on foot, boat, or horseback to explore the wide world of Winthier.
woodcut:
  DisplayName: Woodcutting
  Shorthand: Woodcut
  Description: Grab your axe and cut down trees to collect lumber for your building projects.
