name: Skills
description: skills
author: StarTux
version: 0.4
main: com.winthier.skills.bukkit.BukkitSkillsPlugin
depend: [ Vault, Exploits ]
database: true
commands: {}
permissions:
  skills.skill.*:
    description: Use all skills
    default: op
  skills.skills:
    description: Use the /skills command
    default: op
  skills.admin:
    description: Perform admin tasks
    default: op
commands:
  skills:
    aliases: [ skill, sk ]
    permission: skills.skills
  skillsadmin:
    aliases: [ skilladmin, skadmin ]
    permission: skills.admin
